
#Config to adjust world settings
[World]
	#Enable the villager structures for the computer scientist.
	enableVillagerStructures = true
	#Gives the ap documentation to new players on a world.
	givePlayerBookOnJoin = false
	#Gives the ap documentation to new players on a world.
	#Range: 0 ~ 16000
	villagerStructureWeight = 6

