[general]
	#The material blacklist of this module.
	materialBlacklist = []

[recipes]
	#The materials that should not have crushing recipes added.
	toDustMaterialBlacklist = []
	#The materials that should not have enriching recipes added.
	toCrystalMaterialBlacklist = []
	#The materials that should not have combining recipes added.
	toOreMaterialBlacklist = ["aluminum", "nickel", "amber", "silver", "zinc", "amethyst", "moonstone", "arcane_crystal", "quicksilver", "biotite", "fluorite", "thallasium", "knightmetal", "ironwood", "nebu"]

