
[items]
	#List of cosmetic-only items. All items in this list will have their effects disabled
	#To blacklist all items, use "artifacts:*"
	#Note: blacklisting an item while it is equipped may have unintended side effects
	cosmetics = [""]

	[items.antidote_vessel]
		#Affects how many times a negative effect can be shortened before breaking
		#Setting this to 0 will make this item unbreakable
		#Range: 0 ~ 32767
		durability = 0
		#List of negative effects that can be cancelled by the antidote vessel
		negative_effects = ["minecraft:slowness", "minecraft:mining_fatigue", "minecraft:nausea", "minecraft:blindness", "minecraft:hunger", "minecraft:weakness", "minecraft:poison", "minecraft:wither", "minecraft:levitation"]
		#The maximum duration (in ticks) a negative effect can last with the antidote vessel equipped
		#Range: > 0
		max_effect_duration = 120

	[items.aqua_dashers]
		#Affects how many seconds the player can run on fluids using the aqua dashers before breaking
		#Setting this to 0 will make this item unbreakable
		#Range: 0 ~ 32767
		durability = 0

	[items.bunny_hoppers]
		#Affects how many times the player can jump with the bunny hoppers before breaking
		#Setting this to 0 will make this item unbreakable
		#Range: 0 ~ 32767
		durability = 0
		#Whether Bunny Hoppers should cancel fall damage
		#Fall damage will still be reduced by the jump boost effect
		should_cancel_fall_damage = true
		#The level of the jump boost effect applied by the bunny hoppers
		#0 to not apply a jump boost effect
		#Range: 0 ~ 128
		jump_boost_level = 2

	[items.charm_of_sinking]
		#Affects how many seconds the player can stay underwater using the charm of sinking before breaking
		#Setting this to 0 will make this item unbreakable
		#Range: 0 ~ 32767
		durability = 0

	[items.cloud_in_a_bottle]
		#Affects how many times the player can double jump before breaking
		#Setting this to 0 will make this item unbreakable
		#Range: 0 ~ 32767
		durability = 0
		#Affects double jump height while sprinting
		#1 for no height bonus
		#Range: 0.0 ~ Infinity
		sprint_jump_height_multiplier = 1.5
		#Affects double jump distance while sprinting
		#0 for no distance bonus
		#Range: 0.0 ~ Infinity
		sprint_jump_distance_multiplier = 0.5

	[items.cross_necklace]
		#Affects how many times the player can take damage with the cross necklace before breaking
		#Setting this to 0 will make this item unbreakable
		#Range: 0 ~ 32767
		durability = 0
		#The amount of additional ticks the wearer is invincible after being hit
		#Range: > 0
		invincibility_bonus = 20

	[items.crystal_heart]
		#Affects how much damage the player can take while wearing the crystal heart before breaking
		#Setting this to 0 will make this item unbreakable
		#Range: 0 ~ 32767
		durability = 0
		#The amount additional health applied to the wearer
		#Range: > 0
		health_bonus = 10

	[items.digging_claws]
		#Affects how many blocks the player can break using the digging claws before breaking
		#Setting this to 0 will make this item unbreakable
		#Range: 0 ~ 32767
		durability = 0
		#Mining speed bonus applied by digging claws
		#Range: 0.0 ~ Infinity
		mining_speed_bonus = 3.2
		#The player's base harvest level when wearing digging claws
		#The player's harvest level is equal to MAX(<digging claws harvest level>, <tool harvest level>)
		#Harvest level 0 is no tool, 1 for a wooden tool, 2 stone etc.
		#Range: > 0
		harvest_level = 2
		#The tool types of the digging claws
		#Blocks that do not have these tool types are not affected by the digging claws
		#Use "*" to give digging claws all tool types
		tool_types = ["*"]

	[items.eternal_steak]
		#Affects how many times this item can be eaten before breaking
		#Setting this to 0 will make this item unbreakable
		#Range: 0 ~ 32767
		durability = 0
		#Cooldown (in ticks) before the item can be eaten again
		#Range: > 0
		cooldown = 300
		#Time (in ticks) it takes to eat this item
		#Range: > 0
		use_duration = 24

	[items.everlasting_beef]
		#Affects how many times this item can be eaten before breaking
		#Setting this to 0 will make this item unbreakable
		#Range: 0 ~ 32767
		durability = 0
		#Cooldown (in ticks) before the item can be eaten again
		#Range: > 0
		cooldown = 300
		#Time (in ticks) it takes to eat this item
		#Range: > 0
		use_duration = 24

	[items.feral_claws]
		#Affects how many enemies can be hit using the feral claws before breaking
		#Setting this to 0 will make this item unbreakable
		#Range: 0 ~ 32767
		durability = 0
		#Attack speed bonus applied by feral claws
		#Range: 0.0 ~ Infinity
		attack_speed_bonus = 0.75

	[items.fire_gauntlet]
		#Affects how many enemies can be hit using the fire gauntlet before breaking
		#Setting this to 0 will make this item unbreakable
		#Range: 0 ~ 32767
		durability = 0
		#Duration (equal to total fire damage) for which entities are set on fire
		#Range: > 0
		fire_duration = 8

	[items.flame_pendant]
		#Affects how many times the pendant's effect can be applied before breaking
		#Setting this to 0 will make this item unbreakable
		#Range: 0 ~ 32767
		durability = 0
		#Chance for the pendant to strike an attacker when the wearer is attacked
		#Range: 0.0 ~ 1.0
		strike_chance = 0.4
		#Duration (equal to total fire damage) for which entities are set on fire
		#Range: > 0
		fire_duration = 10

	[items.flippers]
		#Affects how many seconds the player can swim using the flippers
		#Setting this to 0 will make this item unbreakable
		#Range: 0 ~ 32767
		durability = 0
		#Swim speed bonus applied by flippers
		#Range: 0.0 ~ Infinity
		swim_speed_bonus = 1.0

	[items.golden_hook]
		#Affects how many enemies can be killed using the golden hook
		#Setting this to 0 will make this item unbreakable
		#Range: 0 ~ 32767
		durability = 0
		#Affects the amount of recently killed entities to track
		#The amount of extra experience gained from using the golden hook depends on the last x amount of entities killed
		#The fewer entities of the same type recently killed, the more experience is dropped
		#Range: > 1
		tracked_entities = 25
		#Affects the amount of entities of a type that can be killed before entities of that type will no longer drop extra experience
		#If the ratio of entities of the same type recently killed over the total amount of entities recently killed is greater than this value,
		#the extra experience dropped is equal to min_experience_multiplier
		#Range: 0.0 ~ 1.0
		maximum_kill_ratio = 0.5
		#The maximum amount of extra experience (multiplied with total xp) dropped from entities while wearing the golden hook
		#The maximum amount is only dropped when none of the recently killed entities are of the same type
		#Otherwise the amount of experience dropped will be somewhere between the maximum and minimum
		#Range: 0.0 ~ Infinity
		max_experience_multiplier = 5.0
		#The minimum amount of extra experience (multiplied with total xp) dropped from entities while wearing the golden hook
		#1 if entities should drop no extra experience if the maximum kill ratio has been reached
		#Range: 0.0 ~ Infinity
		min_experience_multiplier = 0.0
		#The maximum amount of extra experience dropped by entities
		#Range: > 0
		max_experience = 50

	[items.helium_flamingo]
		#Affects how many seconds the player can fly using the helium flamingo before breaking
		#Setting this to 0 will make this item unbreakable
		#Range: 0 ~ 32767
		durability = 0
		#The maximum amount of time (in ticks) a player can fly using the helium flamingo
		#Set to 0 to allow swimming indefinitely
		#Range: > 0
		max_flight_time = 150
		#The amount of time (in ticks) it takes for the helium flamingo to recharge
		#Range: > 0
		recharge_time = 300

	[items.kitty_slippers]
		#Affects how many creepers the player can attack using the kitty slippers before breaking
		#Setting this to 0 will make this item unbreakable
		#Range: 0 ~ 32767
		durability = 0

	[items.lucky_scarf]
		#Affects how many blocks can be broken using the lucky scarf
		#Setting this to 0 will make this item unbreakable
		#Range: 0 ~ 32767
		durability = 0
		#Fortune bonus applied by the lucky scarf
		#Range: > 0
		fortune_bonus = 1

	[items.night_vision_goggles]
		#Affects how many seconds the night vision effect should apply before breaking
		#Setting this to 0 will make this item unbreakable
		#Range: 0 ~ 32767
		durability = 0

	[items.novelty_drinking_hat]
		#Affects how many items the player can drink using the drinking hat before breaking
		#Setting this to 0 will make this item unbreakable
		#Range: 0 ~ 32767
		durability = 0
		#Drinking duration multiplier applied by the drinking hat
		#Range: 0.0 ~ Infinity
		drinking_duration_multiplier = 0.25
		#Whether the drinking hat should speed up the eating animation as well
		enable_fast_eating = false

	[items.obsidian_skull]
		#Affects how many times the fire resistance effect can be applied before breaking
		#Setting this to 0 will make this item unbreakable
		#Range: 0 ~ 32767
		durability = 0
		#The cooldown (in ticks) on the obsidian skull after applying fire resistance
		#Range: > 0
		cooldown = 1200
		#The duration (in ticks) of the fire resistance effect applied by the obsidian skull after taking fire damage
		#Range: > 0
		fire_resistance_duration = 600

	[items.panic_necklace]
		#Affects how many times the necklace's effect can be applied
		#Setting this to 0 will make this item unbreakable
		#Range: 0 ~ 32767
		durability = 0
		#The level of the speed effect applied by the panic necklace
		#Range: 0 ~ 128
		speed_level = 1
		#The duration (in ticks) of the speed effect applied by the panic necklace
		#Range: > 0
		speed_duration = 160

	[items.plastic_drinking_hat]
		#Affects how many items the player can drink using the drinking hat before breaking
		#Setting this to 0 will make this item unbreakable
		#Range: 0 ~ 32767
		durability = 0
		#Drinking duration multiplier applied by the drinking hat
		#Range: 0.0 ~ Infinity
		drinking_duration_multiplier = 0.25
		#Whether the drinking hat should speed up the eating animation as well
		enable_fast_eating = false

	[items.pocket_piston]
		#Affects how many enemies can be hit using the pocket piston
		#Setting this to 0 will make this item unbreakable
		#Range: 0 ~ 32767
		durability = 0
		#The amount of extra knockback applied by the pocket piston
		#Range: 0.0 ~ Infinity
		knockback_bonus = 1.5

	[items.power_glove]
		#Affects how many enemies can be hit using the power glove
		#Setting this to 0 will make this item unbreakable
		#Range: 0 ~ 32767
		durability = 0
		#The amount of extra attack damage applied by the power glove
		#Range: > 0
		attack_damage_bonus = 4

	[items.running_shoes]
		#Affects how many seconds the player can sprint using the running shoes
		#Setting this to 0 will make this item unbreakable
		#Range: 0 ~ 32767
		durability = 0
		#The amount of extra speed applied by the running shoes
		#Range: 0.0 ~ Infinity
		speed_multiplier = 0.4

	[items.scarf_of_invisibility]
		#Affects how many seconds the invisibility effect should apply before breaking
		#Setting this to 0 will make this item unbreakable
		#Range: 0 ~ 32767
		durability = 0

	[items.shock_pendant]
		#Affects how many times the pendant's effect can be applied before breaking
		#Setting this to 0 will make this item unbreakable
		#Range: 0 ~ 32767
		durability = 0
		#Chance for the pendant to strike an attacker when the wearer is attacked
		#Range: 0.0 ~ 1.0
		strike_chance = 0.25

	[items.snorkel]
		#Affects how many seconds the player can stay underwater using the snorkel before breaking
		#Setting this to 0 will make this item unbreakable
		#Range: 0 ~ 32767
		durability = 0

	[items.steadfast_spikes]
		#Affects how many times the player can be hit while wearing steadfast spikes before breaking
		#Setting this to 0 will make this item unbreakable
		#Range: 0 ~ 32767
		durability = 0

	[items.superstitious_hat]
		#Affects how many enemies can be killed using the superstitious hat
		#Setting this to 0 will make this item unbreakable
		#Range: 0 ~ 32767
		durability = 0
		#Looting bonus applied by the superstitious hat
		#Range: > 0
		looting_bonus = 1

	[items.thorn_pendant]
		#Affects how many times the pendant's effect can be applied before breaking
		#Setting this to 0 will make this item unbreakable
		#Range: 0 ~ 32767
		durability = 0
		#Chance for the pendant to strike an attacker when the wearer is attacked
		#Range: 0.0 ~ 1.0
		strike_chance = 0.5
		#Minimum damage dealt by thorn pendant
		#Damage dealt is a random number between min_damage and max_damage
		#Range: > 0
		min_damage = 2
		#Maximum damage dealt by thorn pendant
		#Range: > 0
		max_damage = 6

	[items.umbrella]
		#Affects how many attacks can be blocked using the umbrella
		#Setting this to 0 will make this item unbreakable
		#Range: 0 ~ 32767
		durability = 0
		#Whether umbrellas can be used as a shield
		is_shield = true

	[items.universal_attractor]
		#Affects how many items can be picked up using the universal attractor
		#Setting this to 0 will make this item unbreakable
		#Range: 0 ~ 32767
		durability = 0
		#The range (in blocks) of the universal attractor
		#Range: > 0
		range = 5
		#Affects how fast items are moved towards the player
		#Range: 0.0 ~ Infinity
		motionMultiplier = 0.6
		#The cooldown (in ticks) after throwing an item
		#Range: > 0
		cooldown = 200

	[items.vampiric_glove]
		#Affects how many enemies can be hit using the vampiric glove
		#Setting this to 0 will make this item unbreakable
		#Range: 0 ~ 32767
		durability = 0
		#The ratio of dealt damage absorbed by the wearer
		#Range: 0.0 ~ Infinity
		absorption_ratio = 0.2
		#The maximum amount of health that can be healed in a single hit
		#Range: > 0
		max_health_absorbed = 6

	[items.villager_hat]
		#Affects how many trades can be completed using the villager hat
		#Setting this to 0 will make this item unbreakable
		#Range: 0 ~ 32767
		durability = 0
		#Affects how much prices are reduced by the villager hat
		#Range: > 0
		reputation_bonus = 100

	[items.whoopee_cushion]
		#Affects how many farts can be farted using the whoopee cushion
		#Setting this to 0 will make this item unbreakable
		#Range: 0 ~ 32767
		durability = 0
		#Affects the amount of farts farted by players wearing the whoopee cushion
		#Range: 0.0 ~ 1.0
		flatulence = 0.125

