
["cheat mode"]
	#Enable Cheat Mode for Operators (/op)
	enableCheatModeForOp = true
	#Enable Cheat Mode for users in Creative Mode
	enableCheatModeForCreative = true
	#Enable Cheat Mode for users who can use /give
	enableCheatModeForGive = false

