
#Client Configuration
[client]

	[client.functionality_options]
		#If challenge sounds should be muted.
		mute_challenges = false
		#Whitelist of advancements to show plaques for.  Leave empty to display for all.
		whitelist = []
		#If task sounds should be muted.
		mute_tasks = false
		#If goal sounds should be muted.
		mute_goals = false

	[client.visual_options]
		#If plaques should show on the top of the screen.
		on_top = true
		#The distance from the top or bottom of the screen, in pixels.
		#Range: 8 ~ 256
		distance = 32
		#If plaques should show for challenge advancements (high-difficulty advancements).
		challenges = true
		#Hide waila/hwyla/jade popups while plaques are showing.
		hide_waila = true
		#If plaques should show for task advancements (normal advancements).
		tasks = true
		#If plaques should show for goal advancements (medium-difficulty advancements).
		goals = true

	[client.duration_options]
		#Duration of the shiny effect fade in for goals.
		#Range: 0.1 ~ 3.0
		goal_effect_fadein = 0.5
		#Duration of the plaques for challenges (minus the effect fade in/out durations).
		#Range: 2.0 ~ 10.0
		challenge_duration = 5.0
		#Duration of the shiny effect fade in for tasks.
		#Range: 0.1 ~ 3.0
		task_effect_fadein = 0.5
		#Duration of the shiny effect fade out for goals.
		#Range: 0.1 ~ 3.0
		goal_effect_fadeout = 1.5
		#Duration of the shiny effect fade out for challenges.
		#Range: 0.1 ~ 3.0
		challenge_effect_fadeout = 1.5
		#Duration of the plaques for tasks (minus the effect fade in/out durations).
		#Range: 2.0 ~ 10.0
		task_duration = 5.0
		#Duration of the plaques for goals (minus the effect fade in/out durations).
		#Range: 2.0 ~ 10.0
		goal_duration = 5.0
		#Duration of the shiny effect fade in for challenges.
		#Range: 0.1 ~ 3.0
		challenge_effect_fadein = 1.25
		#Duration of the shiny effect fade out for tasks.
		#Range: 0.1 ~ 3.0
		task_effect_fadeout = 1.5

