
[general]
	#Whether all players should get an Animal Dictionary when joining the world for the first time.
	giveBookOnStartup = false
	#Lava Opacity for the Lava Vision Potion.
	#Range: 0.01 ~ 1.0
	lavaVisionOpacity = 0.65
	#Whether to disable certain aspects of the Lava Vision Potion. Enable if issues with shaders persist.
	shadersCompat = false
	#Whether bananas should drop from blocks tagged with #alexsmobs:drops_bananas
	bananasDropFromLeaves = true
	#1 out of this number chance for leaves to drop a banana when broken. Fortune is automatically factored in
	#Range: > 0
	bananaChance = 200
	#Whether spiders should target fly mobs.
	spidersAttackFlies = true
	#Whether wolves should target moose mobs.
	wolvesAttackMoose = true
	#Whether polar bears should target seal mobs.
	polarBearsAttackSeals = true
	#Whether lava can be bottled with a right click of a glass bottle.
	lavaBottleEnabled = true
	#Maximum world y-level that cave centipedes can spawn at
	#Range: 0 ~ 256
	caveCentipedeSpawnHeight = 30
	#Maximum world y-level that blobfish can spawn at
	#Range: 0 ~ 256
	blobfishSpawnHeight = 38
	#Whether mimicubes spawns should be restricted solely to the end city structure or to whatever biome is specified in their respective biome config.
	mimicubeSpawnInEndCity = true
	#Whether mimicream can be used to duplicate items.
	mimicreamRepair = true
	#Blacklist for items that mimicream cannot make a copy of. Ex: "minecraft:stone_sword", "alexsmobs:blood_sprayer"
	mimicreamBlacklist = ["alexsmobs:blood_sprayer"]
	#Whether wild raccoons steal food from chests.
	raccoonStealFromChests = true
	#Whether soul vulture spawns should be restricted solely to the nether fossil structure or to whatever biome is specified in their respective biome config.
	soulVultureSpawnOnFossil = true
	#Whether acacia blossoms should drop from blocks tagged with #alexsmobs:drops_acacia_blossoms
	acaciaBlossomsDropFromLeaves = true
	#Whether bone serpents are neutral or hostile.
	neutralBoneSerpents = false
	#Whether fish oil gives players a special levitation effect.
	fishOilMeme = true
	#Whether wandering traders offer items like acacia blossoms, mosquito larva, crocodile egg, etc.
	wanderingTraderOffers = true
	#0 = no mungus biome transformation. 1 = mungus changes blocks, but not chunk's biome. 2 = mungus transforms blocks and biome of chunk.
	#Range: 0 ~ 2
	mungusBiomeTransformationType = 2
	#List of all mungus mushrooms, biome transformations and surface blocks. Each is seperated by a |. Add an entry with a block registry name, biome registry name, and block registry name(for the ground).
	mungusBiomeMatches = ["minecraft:red_mushroom|minecraft:mushroom_fields|minecraft:mycelium", "minecraft:brown_mushroom|minecraft:mushroom_fields|minecraft:mycelium", "minecraft:crimson_fungus|minecraft:crimson_forest|minecraft:crimson_nylium", "minecraft:warped_fungus|minecraft:warped_forest|minecraft:warped_nylium"]
	#Whether guster spawns are limited to when it is raining/thundering.
	limitGusterSpawnsToWeather = true
	#Whether Crimson Mosquitoes can transform into Warped Moscos if attacking a Mungus or any listed creature.
	warpedMoscoTransformation = true
	#List of extra(non mungus) mobs that will trigger a crimson mosquito to become a warped mosquito. Ex: "minecraft:mooshroom", "alexsmobs:warped_toad"
	warpedMoscoMobTriggers = [""]
	#True if straddleboard enchants are enabled.
	straddleboardEnchants = true
	#Whether emu should target skeletons.
	emuTargetSkeletons = true
	#Percent chance for emu leggings to dodge projectile attacks.
	#Range: 0.0 ~ 1.0
	emuPantsDodgeChance = 0.45
	#Percent chance for fungus to grow per each leaf a leafcutter ant returns to the colony.
	#Range: 0.0 ~ 1.0
	leafcutterAntFungusGrowChance = 0.3
	#How many feedings of leaves does a leafcutter colony need in order to regain a worker ant, if below half the max members.
	#Range: 2 ~ 100000
	leafcutterAntRepopulateFeedings = 25
	#Max number of ant entities allowed inside a leafcutter anthill.
	#Range: 2 ~ 100000
	leafcutterAntColonySize = 20
	#Percent chance for leafcutter ants to break leaves blocks when harvesting. Set to zero so that they can not break any blocks.
	#Range: 0.0 ~ 1.0
	leafcutterAntBreakLeavesChance = 0.2
	#Relative volume of cachalot whales compared to other animals. Note that irl they are the loudest animal. Turn this down if you find their clicks annoying.
	#Range: 0.0 ~ 10.0
	cachalotVolume = 2.0
	#Makes eagles teleport back to their owner if they get stuck during controlled flight. Useful for when playing with the Optifine mod, since this mod is the fault of many issues with the falconry system.
	falconryTeleportsBack = false
	#Makes Tarantula Hawks fireproof, perfect if you also want these guys to spawn in the nether.
	fireproofTarantulaHawk = false

	[general.spawning]
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		grizzlyBearSpawnWeight = 3
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		grizzlyBearSpawnRolls = 0
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		roadrunnerSpawnWeight = 6
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		roadrunnerSpawnRolls = 1
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		boneSerpentSpawnWeight = 0
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		boneSeprentSpawnRolls = 30
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		gazelleSpawnWeight = 7
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		gazelleSpawnRolls = 0
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		crocodileSpawnWeight = 15
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		crocSpawnRolls = 1
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		flySpawnWeight = 1
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		flySpawnRolls = 2
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		hummingbirdSpawnWeight = 19.5
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		hummingbirdSpawnRolls = 1
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		orcaSpawnWeight = 1
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		orcaSpawnRolls = 6
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		sunbirdSpawnWeight = 1
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		sunbirdSpawnRolls = 15
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		gorillaSpawnWeight = 12
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		gorillaSpawnRolls = 0
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		crimsonMosquitoSpawnWeight = 7.5
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		crimsonMosquitoSpawnRolls = 0
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		rattlesnakeSpawnWeight = 4
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		rattlesnakeSpawnRolls = 0
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		endergradeSpawnWeight = 5
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		endergradeSpawnRolls = 0
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		hammerheadSharkSpawnWeight = 4
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		hammerheadSharkSpawnRolls = 1
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		lobsterSpawnWeight = 3.5
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		lobsterSpawnRolls = 0
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		komodoDragonSpawnWeight = 2
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		komodoDragonSpawnRolls = 1
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		capuchinMonkeySpawnWeight = 12
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		capuchinMonkeySpawnRolls = 0
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		caveCentipedeSpawnWeight = 4
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		caveCentipedeSpawnRolls = 1
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		warpedToadSpawnWeight = 40
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		warpedToadSpawnRolls = 0
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		mooseSpawnWeight = 5.5
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		mooseSpawnRolls = 0
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		mimicubeSpawnWeight = 20
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		mimicubeSpawnRolls = 0
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		raccoonSpawnWeight = 4
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		raccoonSpawnRolls = 0
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		blobfishSpawnWeight = 15
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		blobfishSpawnRolls = 0
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		sealSpawnWeight = 12.5
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		sealSpawnRolls = 0
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		cockroachSpawnWeight = 1
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		cockroachSpawnRolls = 0
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		shoebillSpawnWeight = 5
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		shoebillSpawnRolls = 0
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		elephantSpawnWeight = 10
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		elephantSpawnRolls = 0
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		soulVultureSpawnWeight = 15
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		soulVultureSpawnRolls = 0
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		snowLeopardSpawnWeight = 10
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		snowLeopardSpawnRolls = 0
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		spectreSpawnWeight = 5
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		spectreSpawnRolls = 5
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		crowSpawnWeight = 2.5
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		crowSpawnRolls = 0
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		alligatorSnappingTurtleSpawnWeight = 10
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		alligatorSnappingTurtleSpawnRolls = 1
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		mungusSpawnWeight = 2
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		mungusSpawnRolls = 1
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		mantisShrimpSpawnWeight = 7.5
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		mantisShrimpSpawnRolls = 0
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		gusterSpawnWeight = 20
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		gusterSpawnRolls = 0
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn. NOTE: By default the warped mosco doesn't spawn in any biomes.
		#Range: 0 ~ 1000
		warpedMoscoSpawnWeight = 1
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		warpedMoscoSpawnRolls = 1000
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		straddlerSpawnWeight = 30
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		straddlerSpawnRolls = 0
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		stradpoleSpawnWeight = 5
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		stradpoleSpawnRolls = 3
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		emuSpawnWeight = 8
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		emuSpawnRolls = 0
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		platypusSpawnWeight = 15
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		platypusSpawnRolls = 0
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		dropbearSpawnWeight = 3.5
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		dropbearSpawnRolls = 1
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		tasmanianDevilSpawnWeight = 5
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		tasmanianDevilSpawnRolls = 0
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		kangarooSpawnWeight = 6
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		kangarooSpawnRolls = 0
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		cachalotWhaleSpawnWeight = 2
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		cachalotWhaleSpawnRolls = 0
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		enderiophageSpawnWeight = 2
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		enderiophageSpawnRolls = 3
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		baldEagleSpawnWeight = 8
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		baldEagleSpawnRolls = 0
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		tigerSpawnWeight = 50
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		tigerSpawnRolls = 0
		#Spawn Weight, added to a pool of other mobs for each biome. Higher number = higher chance of spawning. 0 = disable spawn
		#Range: 0 ~ 1000
		tarantulaHawkSpawnWeight = 5
		#Random roll chance to enable mob spawning. Higher number = lower chance of spawning
		#Range: > 0
		tarantulaHawkSpawnRolls = 1

		[general.spawning.uniqueSpawning]
			#Whether to enable beached cachalot whales to spawn on beaches during thunder storms.
			beachedCachalotWhales = true
			#Percent chance increase for each failed attempt to spawn a beached cachalot whale. Higher value = more spawns.
			#Range: 0 ~ 100
			beachedCachalotWhaleSpawnChance = 5
			#Delay (in ticks) between attempts to spawn beached cachalot whales. Default is a single day. Works like wandering traders.
			#Range: > 0
			beachedCachalotWhaleSpawnDelay = 24000
			#Percent chance for leafcutter anthills to spawn as world gen in each chunk. Set to zero to disable spawning.
			#Range: 0.0 ~ 1.0
			leafcutterAnthillSpawnChance = 0.004999999888241291

