
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 388169
	#The name of the modpack
	modpackName = "Valhelsia 3"
	#The version of the modpack
	modpackVersion = "3.5.2"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

