
#General settings for the mod.
[general]
	#The color at the top of the tooltip gradient.
	borderStart = "c0fdbe3f"
	#The color at the bottom of the tooltip gradient.
	borderEnd = "c0f2683a"
	#The color for the background of the tooltip.
	background = "f01a1932"

