
#Client only settings, mostly things related to rendering
[client]
	#Enable Forge to queue all chunk updates to the Chunk Update thread.
	#May increase FPS significantly, but may also cause weird rendering lag.
	#Not recommended for computers without a significant number of cores available.
	alwaysSetupTerrainOffThread = true
	#EXPERIMENTAL: Enable the Forge block rendering pipeline - fixes the lighting of custom models.
	experimentalForgeLightPipelineEnabled = true
	#When enabled, Forge will show any warnings that occurred during loading.
	showLoadWarnings = true
	#When enabled, makes specific reload tasks such as language changing quicker to run.
	selectiveResourceReloadEnabled = true
	#Set to true to use a combined DEPTH_STENCIL attachment instead of two separate ones.
	useCombinedDepthStencilAttachment = false
	#Forces the use of System.nanoTime instead of glfwGetTime, as the main Util time provider
	forceSystemNanoTime = false

