
#General Config Section
[general]
	#The Client ID of the Discord App to use
	clientID = 874267265518944276
	#Enable/Disable the mod
	enabled = true
	#Enable/Disable debugging mode. WARNING: MAY CAUSE LOG SPAM!
	debugging = false
	#Enable/Disable the in game config screen
	configScreen = false
	#Display the Icon and Pack Name in place of LargeImage from compatible launchers. DOES NOT WORK WITH CUSTOM APPS! ONLY THE DEFAULT ONE!
	launcherIntegration = false
	#Enable/Disabled in-game notifications about new releases
	updater = false
	#Internal Version Number. NO TOUCHY!
	version = 10

#The Game Loading event
[init]
	#Enable/Disable the Game Loading Event
	enabled = true
	#The first line of text under the app name
	description = ""
	#The second line of text under the app name
	state = "Game Starting..."
	#The Asset ID of the image to display as the large image
	largeImageKey = "logo"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Valhelsia 4"
	#The Asset ID of the image to display as the small image
	smallImageKey = "loading"
	#The text that gets displayed when the small image is hovered
	smallImageText = ""
	#The buttons to display on Discord
	buttons = []

#The Main Menu event
[main_menu]
	#Enable/Disable the Main Menu Event
	enabled = true
	#The first line of text under the app name
	description = ""
	#The seconds line of text under the app name
	state = "Main Menu"
	#The Asset ID of the image to display as the large image
	largeImageKey = "logo"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Valhelsia 4"
	#The Asset ID of the image to display as the small image
	smallImageKey = ""
	#The text that gets displayed when the small image is hovered
	smallImageText = ""
	#The buttons to display on Discord
	buttons = []

#The Server List event
[server_list]
	#Enable/Disable the Server List Event
	enabled = true
	#The first line of text under the app name
	description = "Searching for friends"
	#The second line of text under the app name
	state = "Multiplayer Menu"
	#The Asset ID of the image to display as the large image
	largeImageKey = "logo"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Valhelsia 4"
	#The Asset ID of the image to display as the small image
	smallImageKey = ""
	#The text that gets displayed when the small image is hovered
	smallImageText = ""
	#The buttons to display on Discord
	buttons = []

#The Join Game Event
[join_game]
	#Enable/Disable the Join Game Event
	enabled = true
	#The first line of text under the app name
	description = ""
	#The second line of text under the app name
	state = "Joining Game"
	#The Asset ID of the image to display as the large image
	largeImageKey = "logo"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Valhelsia 4"
	#The Asset ID of the image to display as the small image
	smallImageKey = "loading"
	#The text that gets displayed when the small image is hovered
	smallImageText = ""
	#The buttons to display on Discord
	buttons = []

#The Single Player Event
[single_player]
	#Enable/Disable the Single Player Event
	enabled = true
	#The first line of text under the app name
	description = "In %world%"
	#The second line of text under the app name
	state = "Playing Singleplayer"
	#The Asset ID of the image to display as the large image
	largeImageKey = "logo"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Valhelsia 4"
	#The Asset ID of the image to display as the small image
	smallImageKey = ""
	#The text that gets displayed when the small image is hovered
	smallImageText = ""
	#The buttons to display on Discord
	buttons = []

#The Multi Player Event
[multi_player]
	#Enable/Disable the Multi Player Event
	enabled = true
	#The first line of text under the app name
	description = "In %world%"
	#The second line of text under the app name
	state = "Playing Multiplayer"
	#The Asset ID of the image to display as the large image
	largeImageKey = "logo"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Valhelsia 4"
	#The Asset ID of the image to display as the small image
	smallImageKey = ""
	#The text that gets displayed when the small image is hovered
	smallImageText = ""
	#The buttons to display on Discord
	buttons = []

#Fallback event for disabled events
[generic]
	#The first line of text under the app name
	description = ""
	#The second line of text under the app name
	state = ""
	#The Asset ID of the image to display as the large image
	largeImageKey = "logo"
	#The text that gets displayed when the large image is hovered
	largeImageText = "Valhelsia 4"
	#The Asset ID of the image to display as the small image
	smallImageKey = ""
	#The text that gets displayed when the small image is hovered
	smallImageText = ""
	#The buttons to display on Discord
	buttons = []

#Dimension Information Overrides
[dimension_overrides]
	#Allows you to override the displayed values for dimensions
	enabled = false

	#The Dimensions to override
	[[dimension_overrides.dimensions]]
		name = "overworld"
		description = ""
		state = ""
		largeImageKey = ""
		largeImageText = "Valhelsia 4"
		smallImageKey = "mclogo"
		smallImageText = "%mods% mods installed"

	[[dimension_overrides.dimensions]]
		name = "the_nether"
		description = ""
		state = ""
		largeImageKey = ""
		largeImageText = "Valhelsia 4"
		smallImageKey = "the_nether"
		smallImageText = "%mods% mods installed"

	[[dimension_overrides.dimensions]]
		name = "the_end"
		description = ""
		state = ""
		largeImageKey = ""
		largeImageText = "Valhelsia 4"
		smallImageKey = "the_end"
		smallImageText = "%mods% mods installed"

